version: "3"
services:
  mysql:
    image: mariadb:latest
    container_name: gameap.db
    hostname: gameap.db
    environment:
      - MYSQL_ROOT_PASSWORD=gameapdbsuperduperpass
      - MYSQL_DATABASE=gameap
      - MYSQL_USER=gameap
      - MYSQL_PASSWORD=gameap
    restart: always
  web:
    image: nginx:latest
    container_name: gameap.web
    hostname: gameap.web
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./:/var/www
      - ./.dev/nginx-configs/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  php:
    image: knik/php:7.2-fpm-stretch
    container_name: gameap.php
    hostname: gameap.php
    volumes:
      - ./:/var/www
    links:
      - mysql:db
    restart: always
